plugins {
    id 'java'
}

group 'org.mentalizr'
version '0.1-SNAPSHOT'

repositories {
    maven { url "https://jitpack.io" }
    mavenCentral()
}

dependencies {
    implementation libs.ap.utils.core
    implementation libs.ap.utils.io
    implementation libs.ap.configuration
    implementation libs.qos.logback

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}